version: '3'
services:
  productDB:
    image: postgres
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: timtran
      POSTGRES_DB: adidas
    ports:
      - '3309:5432'

  app:
    container_name: tim
    restart: always
    build: .
    ports:
      - '3002:3002'
    links:
      - productDB
