version: '3'
services:
  productDB:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/mysql
      - ./mysql_local.cnf:/etc/mysql/conf.d/mysql_local.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: timtran
      MYSQL_DATABASE: fec
      MYSQL_USER: root
      MYSQL_PASSWORD: timtran
    ports:
      - '3307:3306'
